baseURL = 'https://inkstash.github.io/'
DefaultContentLanguage = 'en'
languageCode = 'en-us'
title = 'InkStash'
copyright = 'InkStash 2023'
theme = 'dear-diary'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
